// Custom icon static resources

import {
  AccountBookOutline,
  AppstoreOutline,
  AreaChartOutline,
  BulbOutline,
  DashboardOutline,
  DashOutline,
  DatabaseOutline,
  DeleteOutline,
  DownloadOutline,
  EditOutline,
  ExceptionOutline,
  GroupOutline,
  InfoOutline,
  LineChartOutline,
  LinkOutline,
  PlusOutline,
  ProfileOutline,
  SettingOutline,
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  InfoOutline,
  BulbOutline,
  ProfileOutline,
  ExceptionOutline,
  LinkOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  AppstoreOutline,
  DashOutline,
  AccountBookOutline,
  DatabaseOutline,
  AreaChartOutline,
  GroupOutline,
  DashboardOutline,
  SettingOutline,
  AppstoreOutline,
  LineChartOutline,
  DownloadOutline,
];
